# Generated by Django 3.1.2 on 2020-10-13 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maniva_webapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
