# Generated by Django 3.0.5 on 2020-10-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maniva_webapp', '0003_locationexpression_project_task_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='referral',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Referral'),
        ),
    ]
