# Generated by Django 3.0.5 on 2020-10-14 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maniva_webapp', '0004_userprofile_referral'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
