# Generated by Django 3.0.5 on 2020-10-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maniva_webapp', '0006_auto_20201015_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='client_name',
            field=models.CharField(max_length=500, verbose_name='Client name'),
        ),
    ]
