# Generated by Django 3.0.5 on 2020-10-16 09:44

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('maniva_webapp', '0007_auto_20201015_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
